# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_stacked.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1424, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1451, 871))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setStyleSheet("")
        self.page1.setObjectName("page1")
        self.Trans_Text = QtWidgets.QLabel(self.page1)
        self.Trans_Text.setGeometry(QtCore.QRect(50, 720, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Trans_Text.setFont(font)
        self.Trans_Text.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.Trans_Text.setObjectName("Trans_Text")
        self.Enter_Button = QtWidgets.QPushButton(self.page1)
        self.Enter_Button.setGeometry(QtCore.QRect(1300, 720, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Enter_Button.setFont(font)
        self.Enter_Button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.Enter_Button.setObjectName("Enter_Button")
        self.Exit_Button = QtWidgets.QPushButton(self.page1)
        self.Exit_Button.setGeometry(QtCore.QRect(1300, 760, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Exit_Button.setFont(font)
        self.Exit_Button.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Exit_Button.setObjectName("Exit_Button")
        self.graphicsView2 = QtWidgets.QGraphicsView(self.page1)
        self.graphicsView2.setGeometry(QtCore.QRect(0, 0, 1451, 821))
        self.graphicsView2.setStyleSheet("border-image: url(:/page1/f8cdd0076ceed5e7ff3bd452c8a3779d.jpg);")
        self.graphicsView2.setObjectName("graphicsView2")
        self.graphicsView2.raise_()
        self.Trans_Text.raise_()
        self.Enter_Button.raise_()
        self.Exit_Button.raise_()
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setStyleSheet("")
        self.page2.setObjectName("page2")
        self.Prev_butt = QtWidgets.QPushButton(self.page2)
        self.Prev_butt.setGeometry(QtCore.QRect(0, 770, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Prev_butt.setFont(font)
        self.Prev_butt.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Prev_butt.setObjectName("Prev_butt")
        self.Next_butt = QtWidgets.QPushButton(self.page2)
        self.Next_butt.setGeometry(QtCore.QRect(1330, 780, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Next_butt.setFont(font)
        self.Next_butt.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.Next_butt.setObjectName("Next_butt")
        self.graphicsView = QtWidgets.QGraphicsView(self.page2)
        self.graphicsView.setGeometry(QtCore.QRect(210, 140, 541, 351))
        self.graphicsView.setMinimumSize(QtCore.QSize(256, 211))
        self.graphicsView.setStyleSheet("border-image: url(:/page2.2/large_thumbnail.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.page2)
        self.graphicsView_2.setGeometry(QtCore.QRect(960, 400, 381, 321))
        self.graphicsView_2.setStyleSheet("border-image: url(:/page 2/570bc77c26db98ff318de807dba1e7f7.jpg);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.checkBox = QtWidgets.QCheckBox(self.page2)
        self.checkBox.setGeometry(QtCore.QRect(970, 750, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page2)
        self.checkBox_2.setGeometry(QtCore.QRect(1060, 750, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page2)
        self.checkBox_3.setGeometry(QtCore.QRect(1150, 750, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.page2)
        self.graphicsView_3.setGeometry(QtCore.QRect(960, 50, 381, 321))
        self.graphicsView_3.setStyleSheet("border-image: url(:/page2.1/56.jpg);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.Load_Data = QtWidgets.QPushButton(self.page2)
        self.Load_Data.setGeometry(QtCore.QRect(640, 760, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Load_Data.setFont(font)
        self.Load_Data.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.Load_Data.setObjectName("Load_Data")
        self.tableWidget = QtWidgets.QTableWidget(self.page2)
        self.tableWidget.setGeometry(QtCore.QRect(160, 520, 591, 51))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page3)
        self.calendarWidget.setGeometry(QtCore.QRect(200, 90, 851, 411))
        self.calendarWidget.setObjectName("calendarWidget")
        self.Exit2_butt = QtWidgets.QPushButton(self.page3)
        self.Exit2_butt.setGeometry(QtCore.QRect(1160, 760, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Exit2_butt.setFont(font)
        self.Exit2_butt.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Exit2_butt.setObjectName("Exit2_butt")
        self.pushButton = QtWidgets.QPushButton(self.page3)
        self.pushButton.setGeometry(QtCore.QRect(0, 767, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1424, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Intelligent Failure Analysis"))
        self.Trans_Text.setText(_translate("MainWindow", "Transformer Failure Analysis"))
        self.Enter_Button.setText(_translate("MainWindow", "Enter"))
        self.Exit_Button.setText(_translate("MainWindow", "Exit"))
        self.Prev_butt.setText(_translate("MainWindow", "Previous"))
        self.Next_butt.setText(_translate("MainWindow", "Next"))
        self.checkBox.setText(_translate("MainWindow", "Power"))
        self.checkBox_2.setText(_translate("MainWindow", "Current"))
        self.checkBox_3.setText(_translate("MainWindow", "Voltage"))
        self.Load_Data.setText(_translate("MainWindow", "Load Data"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Present Value"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Voltage (V)"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current (A)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Power (kW)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Oil Temp (Degree)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "AmbTemp(Degree)"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "50"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "50"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "50"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "555"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "555"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.Exit2_butt.setText(_translate("MainWindow", "Exit Programme"))
        self.pushButton.setText(_translate("MainWindow", "Previous"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

import Photo

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

