# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stacked2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from DIP.Calendar import CalendarWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Trans_Text = QtWidgets.QLabel(self.page)
        self.Trans_Text.setGeometry(QtCore.QRect(10, 600, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Trans_Text.setFont(font)
        self.Trans_Text.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.Trans_Text.setObjectName("Trans_Text")
        self.Enter_Button = QtWidgets.QPushButton(self.page)
        self.Enter_Button.setGeometry(QtCore.QRect(1100, 600, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Enter_Button.setFont(font)
        self.Enter_Button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.Enter_Button.setObjectName("Enter_Button")
        self.Exit_Button = QtWidgets.QPushButton(self.page)
        self.Exit_Button.setGeometry(QtCore.QRect(1100, 630, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Exit_Button.setFont(font)
        self.Exit_Button.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Exit_Button.setObjectName("Exit_Button")
        self.graphicsView2 = QtWidgets.QGraphicsView(self.page)
        self.graphicsView2.setGeometry(QtCore.QRect(0, 0, 1221, 691))
        self.graphicsView2.setStyleSheet("border-image: url(:/page1/f8cdd0076ceed5e7ff3bd452c8a3779d.jpg);")
        self.graphicsView2.setObjectName("graphicsView2")
        self.graphicsView2.raise_()
        self.Trans_Text.raise_()
        self.Enter_Button.raise_()
        self.Exit_Button.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")

        self.calendarWidget = CalendarWidget(self.page_2)
        self.calendarWidget.setGeometry(QtCore.QRect(9, 9, 1181, 451))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")

        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(130, 470, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(10, 470, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(150, 500, 201, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(10, 500, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Exit2_butt = QtWidgets.QPushButton(self.page_2)
        self.Exit2_butt.setGeometry(QtCore.QRect(1130, 620, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Exit2_butt.setFont(font)
        self.Exit2_butt.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.Exit2_butt.setObjectName("Exit2_butt")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 620, 97, 37))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.Display_Graph_1 = QtWidgets.QPushButton(self.page_2)
        self.Display_Graph_1.setGeometry(QtCore.QRect(1010, 500, 101, 41))
        self.Display_Graph_1.setObjectName("Enlarge_Graph_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_1.setGeometry(QtCore.QRect(910, 470, 81, 31))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_2.setGeometry(QtCore.QRect(910, 510, 81, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_3.setGeometry(QtCore.QRect(910, 550, 81, 31))

        self.checkBox_3.setObjectName("checkBox_3")
        self.Load_Data = QtWidgets.QPushButton(self.page_2)
        self.Load_Data.setGeometry(QtCore.QRect(540, 620, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Load_Data.setFont(font)
        self.Load_Data.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.Load_Data.setObjectName("Load_Data")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(600, 475, 300, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1222, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Trans_Text.setText(_translate("MainWindow", "Transformer Failure Analysis"))
        self.Enter_Button.setText(_translate("MainWindow", "Enter"))
        self.Exit_Button.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Failure Probabilty:"))
        #self.label_2.setText(_translate("MainWindow", "Recomended Action:"))
        self.Exit2_butt.setText(_translate("MainWindow", "Exit"))
        self.pushButton.setText(_translate("MainWindow", "Home"))
        self.Display_Graph_1.setText(_translate("MainWindow", "Display Graph "))
        self.checkBox_1.setText(_translate("MainWindow", "Voltage"))
        self.checkBox_2.setText(_translate("MainWindow", "Current"))
        self.checkBox_3.setText(_translate("MainWindow", "Power"))
        self.Load_Data.setText(_translate("MainWindow", "Display Data"))
        self.label_5.setText(_translate("MainWindow", "Select 1 Checkbox to display Graph:"))


import Photos

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
